[buildPlans.Iosevka]
family = "Iosevka"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Iosevka.variants.design]
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
six = "straight-bar"
eight = "two-circles"
nine = "straight-bar"
zero = "slashed"
capital-g  = "toothless-corner-serifless-hooked"
f = "flat-hook-serifless"
j = "flat-hook-serifed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
y = "straight-turn-serifless"
asterisk = "penta-mid"
guillemet = "straight"
lig-ltgteq = "slanted"

[buildPlans.Iosevka.variants.italic]
zero = "slashed"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
six = "straight-bar"
eight = "two-circles"
nine = "straight-bar"
capital-g  = "toothless-corner-serifless-hooked"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-tailed"
g = "single-storey-serifless"
i = "serifed-semi-tailed"
j = "flat-hook-serifed"
k = "straight-serifless"
l = "serifed-semi-tailed"
r = "hookless-serifless"
t = "flat-hook-short-neck"
u = "toothed-serifless"
y = "straight-turn-serifless"
lower-iota = "serifed-semi-tailed"
lower-tau = 'semi-tailed'
asterisk = "penta-mid"
guillemet = "straight"
lig-ltgteq = "slanted"

[buildPlans.Iosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevka.weights.Bold]
shape = 600
menu = 700
css = 600

[buildPlans.Iosevka.widths.Normal]
shape = 575
menu = 5
css = "normal"

[buildPlans.Iosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Iosevka.slopes.Italic]
# angle = 9.4
angle = 10
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.Iosevka.metricOverride]
# cap & ascender: 735 * 1.055
cap = 775
ascender = 775
# xHeight: 535 * 1.055
xHeight = 564
leading = 1350
winMetricAscenderPad = 0
winMetricDescenderPad = 0
powerlineScaleY = 1
powerlineScaleX = 1
powerlineShiftY = 0
powerlineShiftX = 0
# parenSize: 966 * 1.055
parenSize = 1019
# symbolMid: 340 * 1.055
symbolMid = 359
